cask 'penbrew-hardware-hacking' do
  version '0.1'
  sha256 :no_check

  url "https://github.com/feffi/homebrew-penbrew"
  name 'PenBrew Homebrew Tap - Usefull tools'
  homepage 'https://github.com/feffi/homebrew-penbrew'
  license :mit
  stage_only true

  depends_on cask: 'penbrew-prerequisites'

  # Useful Tools
  depends_on formula: 'exiftool'
  depends_on formula: 'ffmpeg'
  depends_on formula: 'faac'
  depends_on formula: 'lame'
  depends_on formula: 'apm-bash-completion'
  depends_on formula: 'boot2docker-completion'
  depends_on formula: 'p7zip'
  depends_on formula: 'brew-cask-completion'
  depends_on formula: 'bash-completion'
  depends_on formula: 'open-completion'
  depends_on formula: 'lynis'
  depends_on formula: 'testdisk'
  depends_on formula: 'ext2fuse'
  depends_on formula: 'ext4fuse'
  depends_on cask: 'handbrake'
  depends_on cask: 'skim'
  depends_on cask: 'sofortbild'
  depends_on cask: 'controlplane'
  depends_on cask: 'cocoapacketanalyzer'
  depends_on cask: 'tuntap'
  depends_on cask: 'adium'
  depends_on cask: 'cyberduck'
  depends_on cask: 'dropbox'
  depends_on cask: 'grandperspective'
  depends_on cask: 'launchcontrol'
  depends_on cask: 'keka'
  depends_on cask: 'gfxcardstatus'
  depends_on cask: 'betterzip'
  depends_on cask: 'freeplane'
  depends_on cask: 'burn'
  depends_on cask: 'coconutbattery'
  depends_on cask: 'tinyumbrella'
  depends_on cask: 'appcleaner'
  depends_on cask: 'alfred'
  depends_on cask: 'qlcolorcode'
  depends_on cask: 'qlmarkdown'
  depends_on cask: 'qlstephen'
  depends_on cask: 'nvalt'
  depends_on cask: 'quicklook-json'
  depends_on cask: 'google-chrome'
  depends_on cask: 'firefox'
  depends_on cask: '1password'
  depends_on cask: 'istat-menus'
  depends_on cask: 'little-snitch'
  depends_on cask: 'bittorrent-sync'
  depends_on cask: 'keepassx'
  depends_on cask: 'filezilla'
  depends_on cask: 'steam'
  depends_on cask: 'gpgtools'
  depends_on cask: 'growlnotify'
  depends_on formula: 'growly'
  depends_on cask: 'audacity'
  depends_on cask: 'clamxav'
  depends_on cask: 'jdownloader'
  depends_on cask: 'openoffice'
  depends_on cask: 'teamviewer'
  depends_on cask: 'tinyumbrella'
  depends_on cask: 'vlc'
  depends_on cask: 'wakeonlan'
  depends_on cask: 'handbrake'
  depends_on cask: 'handbrakecli'
  depends_on cask: 'godot'
  depends_on cask: 'gephi'
  depends_on cask: 'keka'
  depends_on cask: 'controlplane'
  depends_on cask: 'launchcontrol'
  depends_on cask: 'macpass'
  depends_on cask: 'nvalt'
  depends_on cask: 'tftpserver'
  depends_on cask: 'the-unarchiver'
  depends_on cask: 'tinyumbrella'
end